import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { viteSingleFile } from "vite-plugin-singlefile";
import { resolve } from "path";
import { readFileSync } from "fs";
import yaml from "js-yaml";

// Virtual module that exposes styles.yml at build time
const stylesVirtualPlugin = {
  name: "styles-yaml",
  resolveId(id) {
    if (id === "virtual:styles") return "\0virtual:styles";
  },
  load(id) {
    if (id !== "\0virtual:styles") return;
    const raw = readFileSync(resolve("styles.yml"), "utf8");
    const styles = yaml.load(raw);
    return `export default ${JSON.stringify(styles)};`;
  },
};

// vite-plugin-singlefile requires a single entry point per build.
// FIGURE env var selects which figure to build; build.js iterates all.
const figure = process.env.FIGURE;
if (!figure) {
  throw new Error(
    "Set FIGURE env var (e.g. FIGURE=umap vite build). Use `npm run build` to build all.",
  );
}

export default defineConfig({
  plugins: [stylesVirtualPlugin, svelte(), viteSingleFile()],
  build: {
    outDir: "../_figures",
    emptyOutDir: false,
    rollupOptions: {
      input: resolve("src", "figures", figure, "index.html"),
      // index.html is generated by build.js if not present
    },
  },
});
